<script setup>
import { ref } from "vue";
import { ChevronDownIcon } from "@heroicons/vue/20/solid";

const faqs = ref([
  {
    id: 1,
    question: "How do I earn through the affiliate program?",
    answer:
      "Share your link today and start earning commissions from every bet your referrals make.",
  },
  {
    id: 2,
    question: "What are the eligibility requirements?",
    answer:
      "It's completely free with no conditions — just share with others and grow your affiliate network!",
  },
  {
    id: 3,
    question: "How is commission calculated?",
    answer:
      "Earn 30% commission based on the net-positive revenue generated by your referred users.",
  },
  {
    id: 4,
    question: "Can I lose money if my referrals win?",
    answer:
      "When your players win, you share in their success — but you never lose. Even if overall game profits are negative, your revenue balance resets to zero weekly, ensuring no losses carry over.",
  },
  {
    id: 5,
    question: "How can I track my earnings?",
    answer:
      "We have a clear dashboard that displays your current weekly revenue, overall earnings, and a list of the players you've signed up.",
  },
  {
    id: 6,
    question: "When are earnings available for withdrawal?",
    answer:
      "Weekly earnings are calculated from Monday 00:00 EAT to Sunday 23:59 EAT. Your first payment is locked in after a full calendar week since your first referred player starts playing.",
  },
]);

const openId = ref(null);

const toggle = (id) => {
  openId.value = openId.value === id ? null : id;
};
</script>

<template>
  <div class="bg-card rounded-xl p-5 mt-4 space-y-3">
    <h3 class="text-lg font-bold text-foreground">FAQs</h3>

    <div class="space-y-2">
      <div
        v-for="faq in faqs"
        :key="faq.id"
        class="rounded-lg overflow-hidden border border-border/50"
      >
        <button
          class="w-full flex items-center justify-between p-3.5 text-left hover:bg-accent/50 transition-colors"
          @click="toggle(faq.id)"
        >
          <span class="text-sm font-medium text-foreground pr-4">
            {{ faq.question }}
          </span>
          <ChevronDownIcon
            class="w-5 h-5 text-muted-foreground shrink-0 transition-transform duration-200"
            :class="{ 'rotate-180': openId === faq.id }"
          />
        </button>

        <Transition
          enter-active-class="transition-all duration-200 ease-out"
          enter-from-class="max-h-0 opacity-0"
          enter-to-class="max-h-40 opacity-100"
          leave-active-class="transition-all duration-150 ease-in"
          leave-from-class="max-h-40 opacity-100"
          leave-to-class="max-h-0 opacity-0"
        >
          <div v-if="openId === faq.id" class="overflow-hidden">
            <p class="px-3.5 pb-3.5 text-sm text-muted-foreground leading-relaxed">
              {{ faq.answer }}
            </p>
          </div>
        </Transition>
      </div>
    </div>
  </div>
</template>
